### ISSUE TITLE
coroutines

### ISSUE THREAD

**Issue by mattshen** [mattshen/my-docs#2]
## Purpose
- Better understand coroutine benefits
- Know how to apply coroutine in real applications properly

## Task
- [ ] read Wikipedia page to understand its definition
- [ ] play with Kotlin coroutine
- [ ] javascript coroutine (generators)
- [ ] Java coroutines
- [ ] coroutine and thread
- [ ] coroutine and NIO?

**Comment by mattshen** [comment]
##好处 1
- 让异步代码更好写，更好读, e.g. JS async/await
